"""
Module 3: auto_deploy — Automated Deployment & Sync

Takes the _workspaces/ directory generated by Module 2's agents
and deploys it to Firebase Hosting via non-interactive CLI commands.
"""

import json
import shutil
import subprocess
from pathlib import Path
from typing import Dict, List, Optional

WORKSPACE_DIR = Path(__file__).parent / "_workspaces"


def _run_command(cmd: List[str], cwd: Optional[str] = None) -> Dict[str, str]:
    """Run a shell command and capture output."""
    print(f"[auto_deploy] Running: {' '.join(cmd)}")
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=120,
            shell=True,  # needed on Windows
        )
        return {
            "returncode": result.returncode,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        }
    except subprocess.TimeoutExpired:
        return {"returncode": -1, "stdout": "", "stderr": "Command timed out (120s)"}
    except FileNotFoundError:
        return {"returncode": -1, "stdout": "", "stderr": f"Command not found: {cmd[0]}"}


def _check_firebase_cli() -> bool:
    """Check if Firebase CLI is installed and accessible."""
    result = _run_command(["firebase", "--version"])
    if result["returncode"] == 0:
        print(f"[auto_deploy] Firebase CLI found: {result['stdout']}")
        return True
    print("[auto_deploy] Firebase CLI not found. Install with: npm install -g firebase-tools")
    return False


def package_workspace(workspace_dir: str) -> Dict[str, any]:
    """
    Scan workspace and identify deployable files.
    Copies frontend files to a public/ directory for Firebase Hosting.

    Returns:
        Dict with public_dir path and file list.
    """
    ws = Path(workspace_dir)
    if not ws.exists():
        raise FileNotFoundError(f"Workspace not found: {ws}")

    public_dir = ws / "public"
    public_dir.mkdir(exist_ok=True)

    deployed_files = []

    # Collect all HTML/CSS/JS/image files from workspace
    web_extensions = {".html", ".css", ".js", ".json", ".svg", ".png", ".jpg", ".ico", ".webp"}

    for f in ws.rglob("*"):
        if f.is_file() and f.suffix.lower() in web_extensions:
            # Skip if already in public/
            if "public" in f.parts:
                deployed_files.append(str(f.relative_to(ws)))
                continue

            # Copy to public/
            rel = f.relative_to(ws)
            dest = public_dir / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, dest)
            deployed_files.append(str(rel))
            print(f"[auto_deploy] Packaged: {rel}")

    # Ensure at least an index.html exists
    index = public_dir / "index.html"
    if not index.exists():
        # Search for any HTML file and copy it as index.html
        html_files = list(public_dir.rglob("*.html"))
        if html_files:
            shutil.copy2(html_files[0], index)
            print(f"[auto_deploy] Copied {html_files[0].name} -> index.html")
        else:
            # Create a minimal fallback
            index.write_text(
                "<!DOCTYPE html><html><head><title>AutoLogic Deploy</title></head>"
                "<body><h1>Deployment successful</h1><p>No frontend files were generated.</p></body></html>",
                encoding="utf-8",
            )
            print("[auto_deploy] Created fallback index.html")

    print(f"[auto_deploy] Packaged {len(deployed_files)} files -> {public_dir}")
    return {"public_dir": str(public_dir), "files": deployed_files}


def init_firebase(workspace_dir: str, project_id: str) -> bool:
    """
    Create firebase.json and .firebaserc if they don't exist.
    Uses non-interactive approach (no `firebase init`).
    """
    ws = Path(workspace_dir)

    firebase_json = ws / "firebase.json"
    firebaserc = ws / ".firebaserc"

    if not firebase_json.exists():
        config = {
            "hosting": {
                "public": "public",
                "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
                "rewrites": [
                    {"source": "**", "destination": "/index.html"}
                ],
            }
        }
        firebase_json.write_text(json.dumps(config, indent=2), encoding="utf-8")
        print(f"[auto_deploy] Created firebase.json")

    if not firebaserc.exists():
        rc = {"projects": {"default": project_id}}
        firebaserc.write_text(json.dumps(rc, indent=2), encoding="utf-8")
        print(f"[auto_deploy] Created .firebaserc (project: {project_id})")

    return True


def deploy_to_firebase(
    workspace_dir: str,
    firebase_project_id: str,
) -> Dict[str, str]:
    """
    Deploys a local directory to Firebase Hosting.

    Args:
        workspace_dir: Path to the workspace containing generated files.
        firebase_project_id: Firebase project ID for deployment.

    Returns:
        Dict with deployment_status, hosting_url, and logs.
    """
    logs = []

    # Step 1: Check Firebase CLI
    if not _check_firebase_cli():
        return {
            "deployment_status": "failed",
            "hosting_url": "",
            "logs": "Firebase CLI not installed. Run: npm install -g firebase-tools",
        }

    # Step 2: Package workspace
    try:
        package_info = package_workspace(workspace_dir)
        logs.append(f"Packaged {len(package_info['files'])} files")
    except Exception as e:
        return {
            "deployment_status": "failed",
            "hosting_url": "",
            "logs": f"Packaging failed: {e}",
        }

    # Step 3: Initialize Firebase config
    init_firebase(workspace_dir, firebase_project_id)
    logs.append(f"Firebase config ready (project: {firebase_project_id})")

    # Step 4: Deploy (non-interactive)
    deploy_cmd = [
        "firebase", "deploy",
        "--only", "hosting",
        "--project", firebase_project_id,
        "--non-interactive",
    ]
    result = _run_command(deploy_cmd, cwd=workspace_dir)

    if result["returncode"] == 0:
        # Extract hosting URL from output
        hosting_url = f"https://{firebase_project_id}.web.app"
        for line in result["stdout"].split("\n"):
            if "hosting url" in line.lower() or "web.app" in line:
                url_parts = line.split("https://")
                if len(url_parts) > 1:
                    hosting_url = "https://" + url_parts[-1].strip()
                    break

        logs.append(f"Deploy successful: {hosting_url}")
        logs.append(result["stdout"][-500:] if len(result["stdout"]) > 500 else result["stdout"])

        return {
            "deployment_status": "success",
            "hosting_url": hosting_url,
            "logs": "\n".join(logs),
        }
    else:
        error_msg = result["stderr"] or result["stdout"] or "Unknown error"
        logs.append(f"Deploy failed: {error_msg}")

        return {
            "deployment_status": "failed",
            "hosting_url": "",
            "logs": "\n".join(logs),
        }


def generate_deploy_report(deploy_result: Dict[str, str], workspace_dir: str) -> str:
    """Generate a markdown deployment report."""
    ws = Path(workspace_dir)
    files = list(ws.rglob("*"))
    file_count = sum(1 for f in files if f.is_file())

    status_emoji = "OK" if deploy_result["deployment_status"] == "success" else "FAIL"

    report = f"""# AutoLogic Deployment Report

## Status: {status_emoji} {deploy_result['deployment_status'].upper()}

## Hosting URL
{deploy_result.get('hosting_url', 'N/A')}

## Workspace
- Path: `{ws.resolve()}`
- Total files: {file_count}

## Logs
```
{deploy_result.get('logs', 'No logs')}
```
"""
    report_path = ws / "DEPLOY_REPORT.md"
    report_path.write_text(report, encoding="utf-8")
    print(f"[auto_deploy] Report saved: {report_path}")
    return report


# ──────────────────────────────────────────────
# CLI test
# ──────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    from dotenv import load_dotenv
    load_dotenv()

    project_id = os.getenv("FIREBASE_PROJECT_ID", "my-autologic-project")
    ws = sys.argv[1] if len(sys.argv) > 1 else str(WORKSPACE_DIR)

    result = deploy_to_firebase(ws, project_id)
    report = generate_deploy_report(result, ws)
    print(report)
